"""Add Company language tw

Revision ID: a5f528333001
Revises: e5096a5f52a3
Create Date: 2024-11-06 22:18:37.857126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f528333001'
down_revision: Union[str, None] = 'e5096a5f52a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_name_tw', sa.String(length=256), nullable=True))
    op.add_column('company', sa.Column('company_tag_tw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_tag_tw')
    op.drop_column('company', 'company_name_tw')
    # ### end Alembic commands ###
