"""Add Company.id auto_increment

Revision ID: e5096a5f52a3
Revises: cc9e6bbb1828
Create Date: 2024-11-06 17:03:33.174006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5096a5f52a3'
down_revision: Union[str, None] = 'cc9e6bbb1828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
